import './globals.css';
import '../../styles/variables.css';

import { Geist, Geist_Mono } from 'next/font/google';
import { Hind_Siliguri , Montserrat , Lato } from 'next/font/google';

// Register Google Fonts
const hindSiliguri = Hind_Siliguri({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // ✅ REQUIRED
  variable: '--font-hind-siliguri',
  display: 'swap',
});


const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});


const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-montserrat',
  display: 'swap',
});

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  variable: '--font-lato', // ✅ Custom CSS variable
  display: 'swap',
});

export const metadata = {
  title: 'RV',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* All font variables are included in the className here */}
      <body className={`${geistSans.variable} ${geistMono.variable} ${hindSiliguri.variable}  ${montserrat.variable} ${lato.variable}
`}>
        {children}
      </body>
    </html>
  );
}
